apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes/ingress-nginx//deploy/static/provider/kind?ref=controller-v1.8.0
  - bar-app-deployment.yaml
  - bar-service.yaml
  - foo-app-deployment.yaml
  - foo-service.yaml
  - foo-bar-ingress.yaml